name: flashinfo
description: FlashInfo

publish_to: 'none' 

version: 1.0.3
# author: 东潇客 <caidong.xu@dotcunited.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
   # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: ^0.2.0
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.1.1
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.2
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/lianyagang/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2  # flutter_swiper很久不维护，可以使用空安全版本：flutter_swiper_null_safety
  # 启动URL的插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.0.10
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.8.4
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.6.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^2.1.1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.4
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.2.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.1.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.0.0
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  # device_info_plus: 1.0.1
  # 获取手机信息 https://pub.flutter-io.cn/packages/device_info
  device_info: ^2.0.2
  # 获取软件版本信息 https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.2
  # Json转Model https://pub.flutter-io.cn/packages/json_serializable
  json_annotation: ^4.1.0
   # 动画效果 https://github.com/xvrh/lottie-flutter
  lottie: ^1.1.0
  # https://pub.flutter-io.cn/packages/encrypt
  encrypt: ^5.0.1
  # 屏幕适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.0.0+2
  # 刷新框架 https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.1
  # 弹框 https://pub.flutter-io.cn/packages/flutter_picker
  flutter_picker: ^2.0.2
  #动态加载条加载页面
  shimmer: ^2.0.0
  gzx_dropdown_menu: ^3.1.0
  path_drawing: ^0.5.1
  open_file: ^3.2.1
  sign_in_with_apple: ^3.0.0
  http: ^0.13.3
  meta: ^1.3.0
  uuid: ^3.0.4
  linkedin_login: ^2.0.1
  in_app_purchase: ^1.0.6
   # 第三方登录 google firebase等
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  data_finder: ^0.0.7
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  google_sign_in_web: ^0.10.0+2
  scrollable_positioned_list : ^0.2.0-nullsafety.0
  azlistview: ^2.0.0-nullsafety.0
  # 汉字转拼音
  lpinyin: ^2.0.3
  graphview: 1.0.0-nullsafety.1
  photo_view: ^0.12.0
  expandable_text: ^2.2.0
  screenshot: ^1.2.3
#  # 权限控制插件
  # permission_handler: ^8.1.6
#  permission_handler_platform_interface: ^3.6.1
  # 文件保存插件
  image_gallery_saver: 1.7.0
  flutter_share_me: ^1.2.0
  get_it: ^7.2.0
  flutter_tab_indicator_styler: ^2.0.0
  connectivity: ^3.0.6
  appsflyer_sdk: ^6.4.0+1

dev_dependencies:
  
  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  # flutter_driver:
  #   sdk: flutter
  # integration_test:
  #   sdk: flutter
  # 黄金测试
#  flutter_goldens:
#    sdk: flutter
  json_serializable: ^5.0.0
  build_runner: ^2.1.2
  # 单元测试
  test: ^1.16.8
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/me/
    - assets/images/dashboard/
    - assets/images/state/
    - assets/images/personnel/
    - assets/images/product/
    - assets/images/company/
    - assets/images/company/chart/
    - assets/images/search/
    - assets/images/pay/
    - assets/images/brand/
  fonts:
    - family: iconfontFonts
      fonts:
        - asset: assets/fonts/Iconfont.ttf
    - family: iconfontFontsNew
      fonts:
        - asset: assets/fonts/newiconfont.ttf
